--- #YAML:1.0
name:               Tk-MIMEApp
version:            0.03
abstract:           The great new Tk::MIMEApp!
author:
    - jimi <jimi@webu.co.uk>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:            5.006
    Tk:              5
    Tk::MarkdownTk:  0.07
    YAML::Perl:      0.02
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
